// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5lDJee_Ux6bIGUXM_BtA-HcAAdQlj5ww',
    appId: '1:820931279417:web:6c1e5f5db2b208c0ababe8',
    messagingSenderId: '820931279417',
    projectId: 'chat-application-woods',
    authDomain: 'chat-application-woods.firebaseapp.com',
    storageBucket: 'chat-application-woods.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH86aQ7YKtxL_H7hk5Lkgb7uoLle5UEIc',
    appId: '1:820931279417:android:b2b538b1e18a2697ababe8',
    messagingSenderId: '820931279417',
    projectId: 'chat-application-woods',
    storageBucket: 'chat-application-woods.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAjYqLtzXueegdYRGxID4Bx_ToNZxSWoM',
    appId: '1:820931279417:ios:b605bbf850a91861ababe8',
    messagingSenderId: '820931279417',
    projectId: 'chat-application-woods',
    storageBucket: 'chat-application-woods.appspot.com',
    iosBundleId: 'com.chatapp.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAjYqLtzXueegdYRGxID4Bx_ToNZxSWoM',
    appId: '1:820931279417:ios:b605bbf850a91861ababe8',
    messagingSenderId: '820931279417',
    projectId: 'chat-application-woods',
    storageBucket: 'chat-application-woods.appspot.com',
    iosBundleId: 'com.chatapp.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5lDJee_Ux6bIGUXM_BtA-HcAAdQlj5ww',
    appId: '1:820931279417:web:613be3b14c9065c2ababe8',
    messagingSenderId: '820931279417',
    projectId: 'chat-application-woods',
    authDomain: 'chat-application-woods.firebaseapp.com',
    storageBucket: 'chat-application-woods.appspot.com',
  );
}
